### ISSUE TITLE
yoink: error: --config: stat /app/ /config.yaml: no such file or directory

### ISSUE THREAD

**Issue by kylepyke** [MrMarble/yoink#9]
I'm getting the error above, but I don't see any reference to a "/app/" directory in the docs. Should I be mapping this somewhere?

**Comment by kylepyke** [comment]
I should mention, this is in Docker. It seems the config directory isn't being mapped correctly. Here is my compose:

```name: yoink
services:
    yoink:
        volumes:
            - /home/user/appdata/yoink/config.yaml:/config.yaml:ro
        image: ghcr.io/mrmarble/yoink:latest
```
My config is the default with passwords/API keys changed.

**Comment by ramgoat** [comment]
I was able to get past this with the compose file below.  Remove `env_from` you're providing env vars via the config file.

```
services:
  yoink:
    container_name: yoink
    image: "ghcr.io/mrmarble/yoink:${IMAGE_TAG:-latest}"
    env_file: "stack.env"
    volumes:
    - ./config.yaml:/config.yaml:ro
    entrypoint: /app/yoink -c /config.yaml
    restart: no
```

But unfortunately this doesn't seem to be correct just yet - I found your GH issue when troubleshooting this error:
> `panic: runtime error: index out of range [47] with length 46`

Good luck!

**Comment by kylepyke** [comment]
I actually solved this issue:
```
services:
    yoink:
        volumes:
            - /home/user/appdata/yoink/config.yaml:/config.yaml:ro
```
needs to be:

```
services:
    yoink:
        volumes:
          - /path/where/your/config/resides/:/app/ /
```
